name: Build Dolpÿπhin-MMJR APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/upload-artifact@v4

    - name: Set up Java 8
      uses: actions/upload-artifact@v4
      with:
        distribution: temurin
        java-version: '8'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.2

    - name: Grant execute permission for gradlew
      run: chmod +x ./Source/Android/gradlew

    - name: Build APK
      working-directory: ./Source/Android
      run: ./gradlew assembleRelease --no-daemon

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: Dolphin-MMJR-APK
        path: ./Source/Android/app/build/outputs/apk/release/app-release.apk
