name: BuiÙ†ld Dolphin-MMJR APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant gradlew execute permission
        run: chmod +x ./Source/Android/gradlew

      - name: Build APK
        run: ./Source/Android/gradlew :app:assembleDebug

      - name: Copy APK to artifact
        run: cp ./Source/Android/app/build/outputs/apk/debug/app-debug.apk ./app-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: ./app-debug.apk
